- name: Build
  run: npm run build

- name: Deploy to Nginx (atomic)
  run: |
    set -euo pipefail
    [ -d dist ] && [ -f dist/index.html ] || { echo "dist/ não encontrado"; exit 1; }

    RELEASE="/var/www/app/releases/${GITHUB_SHA}"
    sudo mkdir -p "$RELEASE"
    # -a mantém timestamps/links; não usa sudo no workspace
    sudo cp -a dist/. "$RELEASE/"

    # apontar 'current' e ajustar permissões SOMENTE no /var/www
    sudo ln -sfn "$RELEASE" /var/www/app/current
    sudo chown -R www-data:www-data /var/www/app

    sudo nginx -t
    sudo systemctl reload nginx
