name: Build & Deploy to Local VM

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Fix perms & hard clean
        run: |
          sudo chown -R "$(id -u)":"$(id -g)" "$GITHUB_WORKSPACE" || true
          git reset --hard
          git clean -fdx

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'  # ajuste se o lockfile estiver em subpasta

      # ✅ sem mexer no global; define cache por env (user-level)
      - name: Install deps
        env:
          CI: "true"
          npm_config_cache: ${{ runner.temp }}/.npm
        run: npm ci --no-audit --no-fund
