name: Build & Deploy to Local VM

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Debug path
        run: |
          echo "WS=$GITHUB_WORKSPACE"
          pwd
          ls -la

      - name: Fix perms & hard clean
        run: |
          sudo chown -R "$(id -u):$(id -g)" "$GITHUB_WORKSPACE" || true
          git reset --hard
          git clean -fdx
          mkdir -p "$HOME/.npm"
          npm config set cache "$HOME/.npm" --global

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install deps
        env:
          CI: "true"
        run: npm ci

      # - name: Build
      #   run: npm run build
