name: Build & Deploy to Local VM

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: MetasysAlarmViewer/MetasysAlarmViewer  # ajuste se for outro

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Hard clean workspace
        run: |
          git reset --hard
          git clean -fdx               # remove node_modules/.vite/dist/etc
          mkdir -p "$HOME/.npm"
          npm config set cache "$HOME/.npm" --global

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install deps
        env:
          CI: "true"
        run: npm ci
